# Generated by Django 2.2.1 on 2019-05-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=100)),
                ('agency_url', models.CharField(max_length=250)),
                ('agency_timezone', models.CharField(max_length=50)),
                ('agency_lang', models.CharField(max_length=50, null=True)),
                ('agency_phone', models.CharField(max_length=50, null=True)),
                ('agency_fare_url', models.CharField(max_length=250, null=True)),
                ('agency_email', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Agencies',
            },
        ),
    ]
