# Generated by Django 2.2.1 on 2019-05-05 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('route_short_name', models.CharField(blank=True, max_length=10, null=True)),
                ('route_long_name', models.CharField(blank=True, max_length=50, null=True)),
                ('route_desc', models.CharField(blank=True, max_length=250, null=True)),
                ('route_type', models.IntegerField(choices=[(0, 'Tram'), (1, 'Subway'), (2, 'Rail'), (3, 'Bus'), (4, 'Ferry'), (5, 'Cable car'), (6, 'Gondola'), (7, 'Funicular')])),
                ('route_url', models.CharField(blank=True, max_length=250, null=True)),
                ('route_color', models.CharField(blank=True, max_length=10, null=True)),
                ('route_text_color', models.CharField(blank=True, max_length=10, null=True)),
                ('route_sort_order', models.IntegerField(null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='gtfs.Agency')),
            ],
        ),
    ]
