# Generated by Django 2.2.1 on 2019-05-07 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gtfs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=100)),
                ('service_id', models.CharField(max_length=100)),
                ('trip_headsign', models.CharField(blank=True, max_length=100, null=True)),
                ('trip_short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('direction_id', models.IntegerField(choices=[(0, '0'), (1, '1')], null=True)),
                ('block_id', models.CharField(blank=True, max_length=100, null=True)),
                ('wheelchair_accessible', models.CharField(blank=True, choices=[(0, 'No information'), (1, 'Yes'), (2, 'No')], max_length=1, null=True)),
                ('bikes_allowed', models.CharField(blank=True, choices=[(0, 'No information'), (1, 'Yes'), (2, 'No')], max_length=1, null=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtfs.Route')),
            ],
        ),
    ]
